name: Build SmartMouse

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # --- NEW DEBUGGING STEP ---
      - name: List files in the workspace
        run: dir

      - name: Set up MSVC (C++ Compiler)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Upload Finished Application
        uses: actions/upload-artifact@v4
        with:
          name: SmartMouse-App
          path: build/Release/SmartMouse.exe
